INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (1, 'Звезда', 1, 7.20, 1, 1, 1, 'Старейшее в стране, единственное ежедневное издание на белорусском языке. Новости политической,
экономической, хозяйственной и культурной жизни', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (2, 'Коммерсантъ', 2, 13.50, 1, 1, 1, 'Ежедневная российская деловая газета. Достоверно, оперативно и объективно о событиях в бизнесе, политике и обществе', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (3, 'Аргументы и Факты в Беларуси', 3, 7.50, 1, 3, 1, 'Вся информация в одной газете: независимо, взвешенно, объективно. Актуальные интервью, комментарии, эксклюзивные подробности из коридоров власти. Важно каждому: пенсии, налоги, деньги. Глас народа.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (4, 'FORBES/ФОРБС', 4, 24.00, 1, 6, 2, 'Журнал Forbes — один из самых популярных журналов о бизнесе. На страницах Forbes публикуются истории успехов и провалов, рассказы о самых громких проектах, истории жизни известных предпринимателей, новые идеи для бизнеса и инвестиций, журналистские расследования, ежегодные авторитетные рейтинги, раскрываются причины и следствия наиболее значительных событий и т.д.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (5, 'РБК', 5, 20.50, 1, 1, 1, 'Целостная картина дня и анализ ключевых событий, влияющих на принятие решений. Каждое утро по рабочим дням.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (6, 'Журнал РБК', 5, 12.00, 1, 6, 2, 'Самые актуальные тренды в мировой и российской экономике. Новые возможности и ниши для бизнеса.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (7, 'Harvard Business Review - Россия', 6, 32.00, 1, 6, 2, 'Журнал «Harvard Business Review - Россия» считается одним из самых авторитетных изданий по менеджменту в мире. С журналом сотрудничают 480 российских топ-менеджеров и предпринимателей, в каждом номере они делятся с читателями своим опытом.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (8, 'Белорусы и рынок', 7, 4.54, 1, 3, 1, 'Аналитический еженедельник для деловых людей. Рассказывает о важнейших событиях в экономике,
предоставляет объективную деловую информацию, необходимую для принятия решений в ведении
бизнеса.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (9, 'Прессбол', 8, 27.54, 1, 2, 1, 'Публикации по спортивной тематике', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (10, 'Бюллетень Министерства труда и социальной защиты Республики Беларусь', 9, 17.95, 1, 6, 3, 'Официальное издание Министерства труда и социальной защиты: оперативные комментарии к
законодательным актам, советы специалистов-практиков.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (11, 'Вожык', 1, 4.74, 1, 6, 2, 'Республиканский цветной литературно- художественный журнал сатиры и юмора. Публикует фельетоны,
стихи, юморески, пародии, басни, эпиграммы, карикатуры. Издается на белорусском языке.', 'f:\\upload\\Вожык.png');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (12, 'Экономический бюллетень НИЭИ Министерства экономики Республики Беларусь', 10, 18.14, 1, 6, 3, 'Макроэкономика: теория и методология; планирование и прогнозирование; анализ социально -
экономического развития; перспективы развития экономики Беларуси.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (13, 'БелГазета', 11, 8.85, 1, 3, 1, 'Информационно - аналитический еженедельник.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (14, 'Спортивная панорама', 12, 19.77, 1, 1, 1, 'Специализированное издание, которое оперативно знакомит общество с новостями мирового и
национального спорта.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (15, 'Теленеделя', 13, 2.27, 1, 3, 1, 'Газета с телепрограммой на неделю вперѐд, более 60 каналов телевидения. Новости кино,
телевидения, музыки.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (16, 'COSMOPOLITAN РУССКОЕ ИЗДАНИЕ', 14, 5.86, 1, 3, 2, ' «Девушка в стиле Cosmo» молода, независима и энергична. Она сама выбирает свой путь и пытается
стать лучше, красивее, а главное - счастливее, в чем ей помогает ее любимый журнал', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (17, 'ESQUIRE (ЭСКВАЙР)', 14, 5.81, 1, 3, 2, 'Журнал для успешных мужчин', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (18, 'HELLO! (ХЭЛЛОУ!)', 15, 10.26, 1, 2, 2, 'Знаменитый журнал о знаменитых людях. Частная жизнь звезд, интервью, репортажи', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (19, 'NATIONAL GEOGRAPHIC РОССИЯ (НЭШИОНАЛ ДЖИОГРЭФИК РОССИЯ)', 16, 6.53, 1, 6, 2, 'Журнал отличают высочайшего уровня профессиональная фотожурналистика и эксклюзивная информация о
крупнейших и наиболее значимых открытиях, достижениях и исследованиях в области естествознания,
географии, истории, археологии', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (20, 'NATIONAL GEOGRAPHIC TRAVELER (НЭШИОНАЛ ДЖИОГРЭФИК ТРЕВЕЛЕР)', 16, 5.97, 1, 6, 2, 'В журнале собраны лучшие экспертные мнения и вся практическая информация, которая может
понадобиться при планировании поездок. Исключительные фотографии способны передать колорит
местной жизни', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, frequency_id, periodical_category_id, periodical_description, periodical_picture) VALUES (21, 'Вокруг света', 17, 6.00, 1, 6, 2, 'Один из самых популярных российских журналов, публикующий материалы о путешествиях, загадках истории,
новых научных открытиях и технических достижениях, а также рассказы о знаменитых людях', 'f:\\upload\\c325b015-1a3d-42f7-af69-e315d02557ae.jpg');