INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (1, 'Звезда', 1, 7.20, 1, 1, 1, 'Старейшее в стране, единственное ежедневное издание на белорусском языке. Новости политической,
экономической, хозяйственной и культурной жизни', '77d40c51-7147-4246-951b-0382e285a62a.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (2, 'Коммерсантъ', 2, 13.50, 1, 1, 1, 'Ежедневная российская деловая газета. Достоверно, оперативно и объективно о событиях в бизнесе, политике и обществе', '23704f11-0c47-4f19-aee4-e830e63ab9c4.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (3, 'Аргументы и Факты в Беларуси', 3, 7.50, 1, 1, 3, 'Вся информация в одной газете: независимо, взвешенно, объективно. Актуальные интервью, комментарии, эксклюзивные подробности из коридоров власти. Важно каждому: пенсии, налоги, деньги. Глас народа.', '15158dd7-64fd-43b1-b245-a64e63a8348e.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (4, 'FORBES ФОРБС', 4, 24.00, 1, 1, 1, 'Журнал Forbes - один из самых популярных журналов о бизнесе. На страницах Forbes публикуются истории успехов и провалов, рассказы о самых громких проектах, истории жизни известных предпринимателей, новые идеи для бизнеса и инвестиций, журналистские расследования, ежегодные авторитетные рейтинги, раскрываются причины и следствия наиболее значительных событий и т.д.', 'b46173ed-e69d-4243-9ec3-9b7f0d44216c.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (5, 'РБК', 5, 20.50, 1, 1, 1, 'Целостная картина дня и анализ ключевых событий, влияющих на принятие решений. Каждое утро по рабочим дням.', '254b9c75-483e-4870-9bf2-8bc872c32a6f.png');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (6, 'Журнал РБК', 5, 12.00, 1, 2, 6, 'Самые актуальные тренды в мировой и российской экономике. Новые возможности и ниши для бизнеса.', 'edb0a4cc-7325-4d89-88bf-e3890a6d7b8b.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (7, 'Harvard Business Review Россия', 4, 32.00, 1, 1, 1, 'Журнал Harvard Business Review - Россия считается одним из самых авторитетных изданий по менеджменту в мире. С журналом сотрудничают 480 российских топ-менеджеров и предпринимателей, в каждом номере они делятся с читателями своим опытом.', '5abb494b-f4db-4437-b53a-adf92f607993.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (8, 'Белорусы и рынок', 7, 4.54, 1, 1, 3, 'Аналитический еженедельник для деловых людей. Рассказывает о важнейших событиях в экономике,
предоставляет объективную деловую информацию, необходимую для принятия решений в ведении
бизнеса.', 'ea13c6ab-5a4f-43c2-8d31-5b05cb83018d.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (9, 'Прессбол', 8, 27.54, 1, 1, 2, 'Публикации по спортивной тематике', 'e3936443-4328-43ba-85c3-116a336ecb1f.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (10, 'Бюллетень Министерства труда и социальной защиты Республики Беларусь', 9, 17.95, 1, 3, 6, 'Официальное издание Министерства труда и социальной защиты: оперативные комментарии к
законодательным актам, советы специалистов-практиков.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (11, 'Вожык', 1, 4.74, 1, 2, 6, 'Республиканский цветной литературно- художественный журнал сатиры и юмора. Публикует фельетоны,
стихи, юморески, пародии, басни, эпиграммы, карикатуры. Издается на белорусском языке.', '6f7cfc4f-644d-4c97-8367-7bc7313531d3.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (12, 'Экономический бюллетень НИЭИ Министерства экономики Республики Беларусь', 10, 18.14, 1, 3, 6, 'Макроэкономика: теория и методология; планирование и прогнозирование; анализ социально -
экономического развития; перспективы развития экономики Беларуси.', null);
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (13, 'БелГазета', 11, 8.85, 1, 1, 3, 'Информационно - аналитический еженедельник.', 'c52ca0a1-0320-4659-81c3-a95efdf2b2f9.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (14, 'Спортивная панорама', 12, 19.77, 1, 1, 1, 'Специализированное издание, которое оперативно знакомит общество с новостями мирового и
национального спорта.', '07c54875-5e7f-47c6-aa08-694e72d540ca.png');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (15, 'Теленеделя', 13, 2.27, 1, 1, 3, 'Газета с телепрограммой на неделю вперѐд, более 60 каналов телевидения. Новости кино,
телевидения, музыки.', 'b3545d3c-cc28-499b-bcbc-c8859569017f.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (16, 'COSMOPOLITAN РУССКОЕ ИЗДАНИЕ', 4, 5.86, 1, 1, 1, ' Девушка в стиле Cosmo молода, независима и энергична. Она сама выбирает свой путь и пытается
стать лучше, красивее, а главное - счастливее, в чем ей помогает ее любимый журнал', '08f35290-7104-4f16-bba3-f69b9e14c40f.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (17, 'ESQUIRE', 4, 5.81, 1, 1, 1, 'Журнал для успешных мужчин', 'afa25b1f-d1ee-427a-8535-3706a340fbcc.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (18, 'HELLO', 4, 10.26, 1, 1, 1, 'Знаменитый журнал о знаменитых людях. Частная жизнь звезд, интервью, репортажи', '0aad4225-0a49-4536-bfb1-c1ecd7b37f7d.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (19, 'NATIONAL GEOGRAPHIC РОССИЯ', 4, 6.53, 1, 1, 1, 'Журнал отличают высочайшего уровня профессиональная фотожурналистика и эксклюзивная информация о
крупнейших и наиболее значимых открытиях, достижениях и исследованиях в области естествознания,
географии, истории, археологии', 'b3f228b6-7fe1-490d-a3b0-44db985ae096.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (20, 'NATIONAL GEOGRAPHIC TRAVELER', 4, 5.97, 1, 1, 1, 'В журнале собраны лучшие экспертные мнения и вся практическая информация, которая может
понадобиться при планировании поездок. Исключительные фотографии способны передать колорит
местной жизни', '1be3331b-b291-464c-a17c-29632a5af405.jpg');
INSERT INTO periodicals.periodicals (periodical_id, periodical_name, publisher_id, periodical_month_price, periodical_availability, periodical_category_id, frequency_id, periodical_description, periodical_picture) VALUES (21, 'Вокруг света', 17, 6.00, 1, 2, 6, 'Один из самых популярных российских журналов, публикующий материалы о путешествиях, загадках истории,
новых научных открытиях и технических достижениях, а также рассказы о знаменитых людях', '0f0b6085-3e94-4865-a0df-5c740e703fad.jpg');